---
ca_key_file: "{{ ca_dir }}/ca.key"
ca_cert_file: "{{ ca_dir }}/ca.pem"
ca_subject: "/C=US/ST=Example/L=City/O=ExampleOrg/CN=AnsibleLocalCA"
ca_validity_period: 3650
cert_days: 365

cert_dir: "./pki/issued"
ca_dir: "./pki/ansible_ca"

ca_passphrase: "MySuperSecretPassphrase"